services:
  - type: web
    name: fitmanager-routine
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        value: mongodb+srv://username:password@cluster.mongodb.net/fitmanager-routines
      - key: JWT_SECRET
        value: your-super-secure-jwt-secret-key-here
