{
  'build':
    {
      'buildCommand': 'npm install',
      'publishDirectory': '.',
      'env': { 'NODE_VERSION': '18' },
    },
  'deploy': { 'startCommand': 'npm start', 'healthCheckPath': '/health' },
}
