name: Deploy Routine Service

on:
  push:
    branches: [main, master]
    paths:
      - 'backend/routine-service/**'
      - '.github/workflows/deploy-routine-service.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: backend/routine-service/package-lock.json

      - name: Install dependencies
        run: |
          cd backend/routine-service
          npm ci

      - name: Run tests (if any)
        run: |
          cd backend/routine-service
          npm test --if-present

      - name: Deploy to Render
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_ROUTINE_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}
